export const homeObjOne = {
  id: 'about',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited ransactions with zero fees',
  description:
    'Get access to  our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/svg-1.svg'),
  alt: 'Car',
  dark: true,
  dark2: false,
  primary: true,
  darkText: false,
}
export const homeObjTwo = {
  id: 'discover',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'BBBB BBBB',
  headline: 'Unlimited ransactions with zero fees',
  description:
    'Get access to  our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get Started',
  imgStart: true,
  img: require('../../images/svg-2.svg'),
  alt: 'AAAA',
  dark: false,
  dark2: false,
  primary: false,
  darkText: true,
}
export const homeObjThree = {
  id: 'signup',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited ransactions with zero fees',
  description:
    'Get access to  our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/svg-3.svg'),
  alt: 'Car',
  dark: true,
  dark2: false,
  primary: true,
  darkText: false,
}
export const homeObjFour = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'BBBB BBBB',
  headline: 'Unlimited ransactions with zero fees',
  description:
    'Get access to  our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get Started',
  imgStart: true,
  img: require('../../images/svg-4.svg'),
  alt: 'AAAA',
  dark: false,
  dark2: false,
  primary: false,
  darkText: true,
}
export const homeObjFive = {
  id: 'signup',
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: 'Premium Bank',
  headline: 'Unlimited ransactions with zero fees',
  description:
    'Get access to  our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get Started',
  imgStart: false,
  img: require('../../images/svg-5.svg'),
  alt: 'Car',
  dark: true,
  dark2: false,
  primary: true,
  darkText: false,
}
export const homeObjSix = {
  id: 'signup',
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: 'BBBB BBBB',
  headline: 'Unlimited ransactions with zero fees',
  description:
    'Get access to  our exclusive app that allows you to send unlimited transactions without getting charged any fees',
  buttonLabel: 'Get Started',
  imgStart: true,
  img: require('../../images/svg-6.svg'),
  alt: 'AAAA',
  dark: false,
  dark2: false,
  primary: false,
  darkText: true,
}
